version: 2
updates:
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  groups:
    bundler-dependencies:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
- package-ecosystem: bundler
  directory: /features/fixtures/basic-app
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  groups:
    bundler-dependencies:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
- package-ecosystem: docker
  directory: /features/fixtures/basic-app/docker
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  groups:
    docker-dependencies:
      patterns:
      - "*"
  registries:
  - jfrog
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
registries:
  jfrog:
    type: docker-registry
    url: https://jfrog.ais.acquia.io
    username: github_dependabot_token
    password: ${{secrets.JFROG_GITHUB_DEPENDABOT_TOKEN}}
