AllCops:
  TargetRubyVersion: 3.1
  Exclude:
  - '**/*/binstubs/**/*'
  - '**/*/build/**/*'
  - '**/*/vendor/**/*'
  - 'bundle/**/*'
  - 'doc/api/*'
  - 'packer/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'
