# frozen_string_literal: true

require 'bundler/setup'
require 'microbus/rake_task'

# Deployment build tasks.
Microbus::RakeTask.new(:build) do |opts|
  opts.smoke_test_cmd = 'smoke'
end

# Deployment build tasks.
Microbus::RakeTask.new(:build_checksum) do |opts|
  opts.smoke_test_cmd = 'sequel --help'
  opts.checksum = true
end
